format: 1
project:
  name: JsOfOCairo
  version: 2.0.0
  short_descriptions:
    github: OCaml library to reuse Cairo-based drawing code in browser
    readme:
      - "*JsOfOCairo* is an OCaml (4.02.3+) library to reuse Cairo-based drawing code in web browsers."
      - It's an adapter, implementing (a reasonable subset of) the interface of `Cairo OCaml <https://github.com/Chris00/ocaml-cairo/>`_
      - targeting HTML5 canvas elements as exposed to OCaml by `js_of_ocaml <https://ocsigen.org/js_of_ocaml/>`_ (3.0.0+).
    opam: Library to reuse Cairo-based drawing code in web browsers
ocaml:
  versions:
    at_least: 4.02.3
  dependencies:
    build:
      - js_of_ocaml-compiler:
          at_least: 3.0
          less_than: 4.0
      - js_of_ocaml-ppx:
          at_least: 3.0
          less_than: 4.0
      - dune:
          at_least: 1.1.1
    test:
      - General:
          at_least: 0.6.0
      - cairo2:
          at_least: 0.6
          less_than: 0.7
      - conf-npm
    run:
      - js_of_ocaml:
          at_least: 3.0
          less_than: 4.0
