language: c
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - aspcud
    - libcairo2-dev
    - libgif-dev
    - libjpeg8-dev
    - libpango1.0-dev
install:
  - wget --output-document=$HOME/opam2 https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux
  - chmod +x $HOME/opam2
  - test -d $HOME/.opam/$OCAML_VERSION || $HOME/opam2 init --yes --disable-sandboxing --compiler=$OCAML_VERSION
  - $HOME/opam2 update --yes
  - eval `$HOME/opam2 config env`
  - $HOME/opam2 switch list
  - $HOME/opam2 install --yes General$GENERAL_VERSION cairo2$CAIRO2_VERSION conf-npm dune$DUNE_VERSION js_of_ocaml$JS_OF_OCAML_VERSION js_of_ocaml-compiler$JS_OF_OCAML_COMPILER_VERSION js_of_ocaml-ppx$JS_OF_OCAML_PPX_VERSION
  - if $UPGRADE_OPAM; then $HOME/opam2 upgrade --yes; fi
  - $HOME/opam2 list
script:
  - dune build @runtest-full
env:
  - OCAML_VERSION=4.02.3 GENERAL_VERSION=.0.6.0 CAIRO2_VERSION=.0.6 DUNE_VERSION=.1.1.1 JS_OF_OCAML_VERSION=.3.0 JS_OF_OCAML_COMPILER_VERSION=.3.0 JS_OF_OCAML_PPX_VERSION=.3.0 UPGRADE_OPAM=false
  - OCAML_VERSION=4.07.1 UPGRADE_OPAM=true
  - OCAML_VERSION=4.07.1+flambda UPGRADE_OPAM=true
cache:
  directories:
  - $HOME/.opam
