language: c
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
install:
  - opam init --yes
  - opam update --yes
  - opam switch --yes $OCAML_VERSION
  - eval `opam config env`
  - opam switch
  - opam pin --yes --no-action add js_of_ocaml $JS_OF_OCAML_VERSION
  - opam install --yes js_of_ocaml cairo2 ocamlfind
  - opam upgrade --yes  # @todo Why does this recompile js_of_ocaml? (And thus we re-upload the cache at the end)
  - opam list

  - npm install canvas browserify pixelmatch
  - npm list
script:
  - cd src
  - ocamlbuild -use-ocamlfind -plugin-tag "package(js_of_ocaml.ocamlbuild)" drawing_tests_in_command_line.byte drawing_tests_in_javascript.js JsOfOCairo.cma
  - cd ..
  - src/_build/drawing_tests_in_command_line.byte
  - node drawing_tests_in_node.js
env:
  - OCAML_VERSION=4.02.2 JS_OF_OCAML_VERSION=2.8
  - OCAML_VERSION=4.04.0 JS_OF_OCAML_VERSION=2.8.4
cache:
  directories:
  - $HOME/.opam
